//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aula
    {
        public int ID { get; set; }
        public int Custo { get; set; }
        public int Horario_ID { get; set; }
        public int Professor_ID { get; set; }
        public int Opiniao_ID { get; set; }
        public int Disciplina_ID { get; set; }
        public int Cliente_ID { get; set; }
    
        public virtual Horario Horario { get; set; }
        public virtual Professor Professor { get; set; }
        public virtual Disciplina Disciplina { get; set; }
        public virtual Cliente Cliente { get; set; }
    }
}
