//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fatura
    {
        public int ID { get; set; }
        public int Cliente_ID { get; set; }
        public int Aula_ID { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
