//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opiniao
    {
        public long ID { get; set; }
        public int Avaliacao { get; set; }
        public string Texto { get; set; }
        public int Professor_ID { get; set; }
    
        public virtual Professor Professor { get; set; }
    }
}
