//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido_Aula
    {
        public int ID { get; set; }
        public int Cliente_ID { get; set; }
        public int Disciplina_ID { get; set; }
        public string Nome_Educando { get; set; }
        public int Resultados { get; set; }
        public string Observacao { get; set; }
        public Nullable<int> Horario_ID { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Horario Horario { get; set; }
    }
}
