//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class teachmeDB : DbContext
    {
        public teachmeDB()
            : base("name=teachmeDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aula> Aula { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Disciplina> Disciplina { get; set; }
        public virtual DbSet<Fatura> Fatura { get; set; }
        public virtual DbSet<Horario> Horario { get; set; }
        public virtual DbSet<Opiniao> Opiniao { get; set; }
        public virtual DbSet<Pedido_Aula> Pedido_Aula { get; set; }
        public virtual DbSet<Professor> Professor { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
